export const styles = {
    mainBlock: {
      width: '100%',
      height: '100%',
      backgroundColor: 'rgb(120, 200, 230)',
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'center',
      flexDirection: 'column',
      position: 'relative',
    },
    tittle: {
      color: 'aliceblue',
      fontSize: 56,
      fontFamily: "'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif",
      margin: 20,
    },
    ScoreElem: {
      width: '85%',
      backgroundColor: 'lightblue',
      padding: 5,
      borderRadius: 25,
      color: 'aliceblue',
      fontSize: 32,
      textAlign: 'center',
      margin: 20,
    },
    noteElemSmall: {
      width: '85%',
      backgroundColor: 'lightblue',
      padding: 5,
      borderRadius: 25,
      color: 'aliceblue',
      fontSize: 20,
      textAlign: 'center',
      margin: 10,
    },
    moveZone: {
      width: '85%',
      aspectRatio: 1 / 1,
      backgroundColor: 'lightblue',
      borderRadius: 25,
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'center',
    },
    clickButton: {
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'center',
      width: 170,
      height: 170,
      borderRadius: 50,
      backgroundColor: 'whitesmoke',
    },
    buttonImg: {
      width: 150,
      height: 150,
    },
    winBlock: {
      position: 'absolute',
      zIndex: 2,
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'center',
      flexDirection: 'column',
      width: '90%',
      aspectRatio: 1 / 1,
      backgroundColor: 'white',
      borderRadius: 25,
    },
    winBlockContent: {
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'center',
      flexDirection: 'row',
    },
    winText: {
      fontSize: 24,
      color: 'black',
    },
    balsImg: {
      width: 50,
      height: 50,
    },
    resBtn: {
      width: 80,
      fontSize: 24,
      backgroundColor: 'lightblue',
    },
    scoreBlock: {
      display:"flex",
      justifyContent:"center",
      alignItems:"center",
      width: '98%',
      height: 'auto',
      backgroundColor: 'aliceblue',
      borderRadius: 25,
    },
  };
  